name: Build Wheels
on:
  workflow_dispatch:

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [
            {
              name: "Ubuntu 22.04",
              family: "linux",
              runner: "ubuntu-22.04",
              archs: "x86_64",
            },
            {
              name: "Ubuntu 22.04",
              family: "linux",
              runner: "ubuntu-22.04-arm",
              archs: "aarch64",
            }
          ]
    name: Build Wheels | ${{ matrix.os.name }} | ${{ matrix.os.archs }}
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v5
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_SKIP: >
            cp38*
            cp39*
            *musllinux*
          CIBW_ARCHS: ${{ matrix.os.archs }}
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
          CIBW_TEST_COMMAND: cabextract --version && winetricks --version
      - uses: actions/upload-artifact@v7
        with:
          name: python-wheels-${{ matrix.os.runner }}
          path: ./wheelhouse/*.whl
  upload_wheels:
    name: Upload Wheels
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    needs: build_wheels
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: "."
          pattern: python-wheels-*
          merge-multiple: true
      - run: |
          ls
          mkdir -p ./dist
          mv *.whl ./dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
