name: Build Wheels
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [
            {
              name: "Ubuntu 22.04",
              family: "linux",
              runner: "ubuntu-22.04",
              archs: "x86_64",
            },
            {
              name: "Ubuntu 22.04",
              family: "linux",
              runner: "ubuntu-22.04-arm",
              archs: "aarch64",
            }
          ]
    name: Build Wheels | ${{ matrix.os.name }} | ${{ matrix.os.archs }}
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v5
      - name: Build wheels
        uses: pypa/cibuildwheel@v4.1.0
        env:
          CIBW_SKIP: >
            cp39*
          CIBW_ARCHS: ${{ matrix.os.archs }}
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
          CIBW_TEST_COMMAND: cabextract --version && winetricks --version
      - uses: actions/upload-artifact@v7
        with:
          name: python-wheels-${{ matrix.os.runner }}
          path: ./wheelhouse/*.whl
  release_wheels:
    name: Release Wheels
    runs-on: ubuntu-latest
    needs: build_wheels
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: "."
          pattern: python-wheels-*
          merge-multiple: true
      # *.whl
      - id: get-version
        run: |
          echo "version=$(perl -ne 'print $1 if /PROJECT_VERSION = "([\d\.]+)"/' build_backend/local_backend.py)" >> $GITHUB_OUTPUT
      - id: release-create
        run: |
          if ! gh release view ${{ steps.get-version.outputs.version }} ; then
            gh release create ${{ steps.get-version.outputs.version }} --notes-from-tag ./*.whl
          fi
        env:
          GH_TOKEN: ${{ github.token }}

